version: "2"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      DNS: "jdbc:mariadb://db/spotitube?user=root&password=root"
    ports:
    - "8090:8080"
    depends_on:
    - db
  db:
    container_name: db
    image: mariadb:10.3.10-bionic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotitube
      MYSQL_USER: spotitube
      MYSQL_PASSWORD: spotitube
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
