version: "2"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      DSN: "jdbc:mariadb://db/spotitube?user=root&password=root"
    ports:
    - "8090:8080"
    depends_on:
    - db
  db:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotitube
      MYSQL_USER: spotitube
      MYSQL_PASSWORD: spotitube
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"